"""create site table

Revision ID: 98847ed4d18c
Revises: 5fccc3f2a78b
Create Date: 2025-04-09 16:15:37.852229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98847ed4d18c'
down_revision = '5fccc3f2a78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('app_password', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('site')
    with op.batch_alter_table('scheduled_posts', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_scheduled_posts_site_id', 'sites', ['site_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scheduled_posts_site_id', type_='foreignkey')
        batch_op.alter_column('site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    op.create_table('site',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('app_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='site_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='site_pkey')
    )
    op.drop_table('sites')
    # ### end Alembic commands ###
